### ISSUE TITLE
Add Graphics Elements

### ISSUE THREAD

**Issue by LagTag** [bbulpett/zebra-zpl#30]
Aside from the Box, none of the built in graphics element are implemented yet.

- [x] **Graphic circle** - PR #31, #42
^GC diameter, thickness, color 

- [x] **Graphic diagonal line** - PR #32, #42
^GD width, height, thickness, color, orientation	

- [X] **Graphic ellipse** #42
^GE width, height, thickness, color
	
- [x]  **Graphic symbol** #42
^GS orientation, height, width	

- [x] ~Also the box element is already included, but does not have the corner rounding or color attributes included.~ Fixed by PR #33 

- [x] ~Eventually it may be useful to add in a module for the related graphics values.~ Covered in #42
